// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "PasswordML",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "PasswordML",
            targets: ["AppModule"],
            bundleIdentifier: "cmd.PasswordML",
            teamIdentifier: "X8N8SYJJ36",
            displayVersion: "2.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources"),
                .process("LICENSE")
            ]
        )
    ]
)